version: ${version}
#设定合成表是否在玩家合成时进行检测
#设定为false时,合成表将不进行对应项的检测
#例如,将exp设置为false,则合成表的spendExp配置将不会生效
recipeCheck:
  exp: true
  vault: true
  points: true
  permission: true

#是否屏蔽原版配方
removeVanillaRecipe:
  #工作台配方
  crafting_table: false
  #熔炉配方
  furnace: false
  #高炉配方
  blasting: false
  #烟熏炉配方
  smoking: false
  #营火配方
  campfire: false
  #锻造台配方
  smithing: false
  #切石机配方
  stoneCutting: false
  #村民交易配方
  merchant: false
  #复杂配方, 例如织布机等除了以上列出的类型的配方
  others: false

messages:
  #使用命令的一些消息
  commands:
    noPerm: '&c你没有使用该命令的权限'
    noArgs: '&c请输入子命令以执行'
    nullArg: '&c不存在的子命令'
    reload: '&a插件重载成功'
    version: '&a插件版本: %version%'
    missingParam: '&c缺少参数，请检查输入是否正确'
    playerOnly: '&c此命令只能玩家使用!'
    import: '&a导入成功'
    notExist: '&c配方不存在'
    removed: '&a配方已移除'
  #插件加载过程中的一些消息
  load:
    finish: '&a插件加载完毕'
    vaultSuccess: '&a发现经济插件,已挂钩'
    vaultFailed: '&c未发现经济插件,金钱检查将不会生效'
    pointsSuccess: '&a发现点券插件,已挂钩'
    pointsFailed: '&c未发现点券插件,点券检查将不会生效'
    itemsAdderSuccess: '&a发现ItemsAdder,已挂钩'
    itemsAdderFailed: '&c未发现ItemsAdder'
