name: Craftorithm
version: '${version}'
description: Craft recipes management system
main: pers.yufiria.craftorithm.Craftorithm
api-version: '1.19'
load: POSTWORLD
softdepend:
  - Vault
  - LuckPerms
  - PlayerPoints
  - PlaceholderAPI
  - ItemsAdder
  - Oraxen
  - MythicMobs
  - NeigeItems
  - MMOItems
  - EcoEnchants
  - EcoItems
  - ExecutableItems
  - SCore
  - Nexo
  - AzureFlow
authors: [ YufiriaMazenta ]
folia-supported: true
website: https://github.com/YufiriaMazenta/Craftorithm
