template_shaped:
  #合成表的命名空间ID,只能使用英文小写字母,".", "_", "/"和数字，为使用/recipe命令解锁配方时的ID
  key: 'oasis.recipe.template'
  #合成表的合成物品，使用results:开头可以调用results.yml文件定义的物品
  result: 'results:result1'
  #合成表合成物品的数量,锻造台配方此项无效
  #合成表的类型,shaped为有序,shapeless为无序,furnace为熔炉,smithing为锻造台
  type: 'shaped'
  #设置合成需要花费多少等级,数据只支持整数,只有工作台配方支持
  spendLvl: 10
  #设置合成需要花费多少金钱,数据只支持整数,只有工作台配方支持
  spendMoney: 10
  #设置合成需要花费多少金钱,数据只支持整数,只有工作台配方支持
  spendPoints: 10
  #检测玩家是否拥有合成的权限
  perm: 'oasis.recipe.template'
  #合成表的合成物品，使用items:开头可以调用item.yml文件定义的物品，
  items:
    - 'items:item1 items:item1 items:item1'
    - 'AIR AIR AIR'
    - 'AIR AIR AIR'

template_shapeless:
  key: 'oasis.recipe.template2'
  result: 'results:result2'
  type: 'shapeless'
  #合成表所需物品,顺序无关,只取前9个物品
  items:
    - 'items:item2'

template_cooking:
  key: 'oasis.recipe.template3'
  result: 'results:result1'
  #烧炼类配方,有furnace(熔炉),campfire("营火"),blasting("高炉"),smoking("烟熏炉")四类
  type: 'furnace'
  #熔炉的烧炼物品,只取第一个物品
  items:
    - 'items:item1'
  #熔炉配方的特有属性,设定烧炼后给予多少经验值
  exp: 0
  #熔炉配方的特有属性,设定配方烧炼的时间
  time: 10

template_smithing:
  key: 'oasis.recipe.template4'
  result: 'DIAMOND_SWORD'
  type: 'smithing'
  #锻造台合成配方,第一行为第一个槽,第二行为第二个槽
  items:
    - 'IRON_SWORD'
    - 'items:item1'

template_stoneCutting:
  key: 'oasis.recipe.template5'
  result: 'results:result1'
  #切石机配方
  type: 'stoneCutting'
  #切石机的原料,只取第一个物品
  items:
    - 'items:item1'
template_random_furnace:
  key: 'oasis.recipe.template6'
  #在此处配置每个结果的概率, 若概率总和超过1, 则超过1部分的概率将无效
  #若概率总和小于1, 则小于1的部分将烧炼出空物品
  result:
    - 'results:result1 0.5'
    - 'results:result2 0.4'
    - 'STONE 0.1'
  #furnace(熔炉),campfire("营火"),blasting("高炉"),smoking("烟熏炉")均支持随机配方
  type: 'random_furnace'
  items:
    - 'GRASS_BLOCK'
  exp: 0
  time: 10